import { Course } from "@/types/course";

export const courses: Course[] = [
  {
    id: "7-day-dropshipping-sprint",
    title: "The 7-Day Dropshipping Sprint",
    emoji: "📦",
    shortDescription: "Launch a profitable store and make your first sale in one week using AI-powered tools.",
    fullDescription: "Launch Your Store and Make Your First Sale in One Week. This comprehensive 7-day program takes you from zero to your first sale using Hustle Lab's AI-powered tools. No guesswork, no fluff—just a proven system that helps you build, launch, and scale a real dropshipping business.",
    difficulty: "Beginner",
    estimatedTime: "7 days (1-2 hours per day)",
    toolsUsed: [
      "biz-idea",
      "dropship-goldmine",
      "name-forge",
      "offer-builder",
      "ad-copy-lab"
    ],
    prerequisites: [
      "Hustle Lab Pro subscription",
      "$10-20 ad budget for testing",
      "Shopify or Wix account (14-day free trial available)",
      "Basic understanding of e-commerce"
    ],
    expectedOutcomes: [
      "Launch a professional dropshipping store from scratch",
      "Choose a profitable niche with trending products",
      "Create a complete brand identity (name, logo, colors)",
      "Set up high-converting product pages and offers",
      "Launch and optimize Meta ad campaigns",
      "Make your first sale within 7 days",
      "Build a 30-day growth roadmap for $1,000+ revenue"
    ],
    modules: [
      {
        id: "day-1",
        title: "DAY 1: Find Your Million-Dollar Niche",
        duration: "Day 1 - 30 minutes",
        toolsUsed: ["biz-idea", "dropship-goldmine"],
        content: `**Today's Goal:**
Choose a profitable niche and find 3–5 winning products you can sell immediately.

**What You're Building Today:**
Your foundation. No store can succeed without a focused niche and products people actually want to buy. Today, you're using AI to cut through the noise and find what's already working.

**Step-by-Step Walkthrough:**

**Step 1: Fire Up the Biz-Idea Reactor 💡**
- Open HustleLab and navigate to Biz-Idea Reactor
- Enter your interests or leave it blank for AI suggestions
- Review 5–10 niche ideas generated by the tool
- Look for niches with high demand, low saturation, and emotional appeal (fitness, pets, self-care, home improvement)

**Step 2: Validate with Dropship Goldmine 📦**
- Jump into Dropship Goldmine
- Enter your chosen niche (e.g., "pet accessories" or "home gym equipment")
- Let AI pull trending products from suppliers
- Filter by: order volume, profit margin, and shipping time
- Bookmark 3–5 products that have strong visuals and reviews

**Step 3: Quick Market Check**
- Search your top product on Amazon, TikTok, and Instagram
- Check if there's UGC (user-generated content) around it
- If people are already creating content about it, that's your green light

**HustleLab Tools Used:**
- 💡 Biz-Idea Reactor → niche selection
- 📦 Dropship Goldmine → product research

**Platform Actions:**
None yet — today is pure research and decision-making

**Daily Mission:**
Write down your niche and your top 3 products in a Google Doc or Notes app. Include the supplier link and estimated profit per unit.

**Motivational Close:**
You just did in 30 minutes what most people spend weeks overthinking. You have your niche. You have your products. Now let's build the brand around them.`
      },
      {
        id: "day-2",
        title: "DAY 2: Build Your Brand Identity",
        duration: "Day 2 - 1-2 hours",
        toolsUsed: ["name-forge"],
        content: `**Today's Goal:**
Create a memorable brand name, logo, and visual identity that makes your store look legit from day one.

**What You're Building Today:**
Your brand. This is what people will remember, share, and trust. You're not just another dropshipper — you're building something that feels real.

**Step-by-Step Walkthrough:**

**Step 1: Generate Your Brand Name ⚡**
- Open Name Forge in HustleLab
- Enter your niche + a few keywords (e.g., "pet," "premium," "cozy")
- Review 20+ brand name options
- Pick one that's short, memorable, and available as a .com domain
- Check availability on Namecheap or GoDaddy

**Step 2: Design Your Logo 🎨**
- Head to Logo Maker
- Enter your brand name and select your niche
- Choose a style: minimal, bold, playful, or elegant
- Download 3–5 logo variations (with and without text)
- Save as PNG with transparent background

**Step 3: Set Your Brand Colors**
- Pick 2–3 colors that match your niche vibe
- Use a tool like Coolors.co or let Logo Maker suggest a palette
- Write them down (hex codes) — you'll use these everywhere

**Step 4: Create a Simple Brand Guide**
In a doc, write:
- Brand name
- Tagline (1 sentence: what you sell + who it's for)
- Color palette
- Font style (clean and modern works for most niches)

**HustleLab Tools Used:**
- ⚡ Name Forge → brand name
- 🎨 Logo Maker → logo design

**Platform Actions:**
- Register your domain (optional but recommended)
- Create a branded email (use Gmail or domain email)

**Daily Mission:**
Post your logo and brand name in a story or tweet. Tag it #7DaySprint. Accountability = momentum.

**Motivational Close:**
Your brand exists now. It has a name, a face, and a vibe. People will buy from brands, not random stores. You're already ahead of 90% of beginners.`
      },
      {
        id: "day-3",
        title: "DAY 3: Build Your Store in Under 2 Hours",
        duration: "Day 3 - 2 hours",
        toolsUsed: ["offer-builder"],
        content: `**Today's Goal:**
Set up a live Shopify or Wix store with your products, branding, and checkout ready to go.

**What You're Building Today:**
Your storefront. This is where the magic happens. No fluff, no distractions — just a clean, conversion-focused store.

**Step-by-Step Walkthrough:**

**Step 1: Choose Your Platform**
- Shopify (recommended): 14-day free trial, built for e-commerce
- Wix: easier for beginners, decent e-commerce tools
- Sign up and pick a clean, mobile-friendly theme

**Step 2: Use Store Layout Wizard 🏗️**
- Open Store Layout Wizard in HustleLab
- Enter your niche and product types
- AI generates a homepage structure: hero section, featured products, trust badges, FAQ
- Follow the layout and replicate it in your Shopify/Wix editor

**Step 3: Add Your Products**
- Upload product photos from your supplier
- Write product titles (keep them benefit-focused)
- Use Offer Builder 🎁 to generate compelling product descriptions
- Set your pricing: cost + 2–3x markup (aim for $15–$50 profit per item)

**Step 4: Essential Pages**
- Create: Home, Shop, About Us, Contact, Shipping Policy, Refund Policy
- Use AI or templates for policy pages (Shopify has built-in generators)

**Step 5: Connect Payment & Shipping**
- Add PayPal and Stripe (or Shopify Payments)
- Set shipping zones and rates (or offer free shipping and bake it into price)
- Enable email notifications for orders

**Step 6: Add Trust Elements**
- Security badges (SSL, payment icons)
- Reviews section (use app like Loox or Judge.me)
- Live chat widget (Tidio or Gorgias free plan)

**HustleLab Tools Used:**
- 🏗️ Store Layout Wizard → store structure
- 🎁 Offer Builder → product descriptions

**Platform Actions:**
- Shopify or Wix account created
- Theme installed
- Products uploaded
- Payments connected

**Daily Mission:**
Place a test order on your own store. Make sure everything works: cart, checkout, email confirmation.

**Motivational Close:**
Your store is live. You can send someone a link right now and they can buy from you. That's powerful. Most people never get this far.`
      },
      {
        id: "day-4",
        title: "DAY 4: Create Irresistible Offers & Upsells",
        duration: "Day 4 - 1 hour",
        toolsUsed: ["offer-builder"],
        content: `**Today's Goal:**
Increase your average order value by 30–50% using smart upsells, bundles, and urgency tactics.

**What You're Building Today:**
Profit maximizers. Every customer is valuable — your job is to make the most of every transaction without being pushy.

**Step-by-Step Walkthrough:**

**Step 1: Build Product Bundles 🎁**
- Use Offer Builder to create 2–3 bundle ideas
- Example: "Starter Kit," "Best Seller Bundle," "Complete Set"
- Offer a discount (10–15% off) when bought together
- Add bundles as separate products on your store

**Step 2: Add Upsells with Upsell Creator 💰**
- Open Upsell Creator in HustleLab
- Input your main product
- AI suggests complementary upsell/cross-sell items
- Install a Shopify app like Zipify OCU, UpCart, or Honeycomb
- Set up post-purchase or cart upsells

**Step 3: Create Urgency Without Being Sleazy**
- Add countdown timers to product pages (use apps like Hurrify)
- Show stock levels: "Only 7 left in stock"
- Offer limited-time discounts for first-time buyers

**Step 4: Write a Killer Welcome Offer**
- Use Offer Builder to create a popup or banner offer
- Example: "Get 15% off your first order + free shipping"
- Install an email capture popup (Privy, Klaviyo, or Shopify native)

**HustleLab Tools Used:**
- 🎁 Offer Builder → bundles and promotions
- 💰 Upsell Creator → upsell strategy

**Platform Actions:**
- Install upsell app on Shopify/Wix
- Add bundles as products
- Set up email popup with discount code

**Daily Mission:**
Write down your average order value (AOV) goal. If your product is $30, aim for $45–50 with upsells.

**Motivational Close:**
You're not just selling products anymore. You're building a system that prints profit. One customer, multiple revenue streams.`
      },
      {
        id: "day-5",
        title: "DAY 5: Launch Your First Ad Campaign",
        duration: "Day 5 - 1-2 hours",
        toolsUsed: ["ad-copy-lab"],
        content: `**Today's Goal:**
Create and launch a Meta (Facebook/Instagram) ad campaign with scroll-stopping creative and copy.

**What You're Building Today:**
Your customer acquisition engine. Organic is great, but paid ads bring speed. Today, you learn how to buy traffic that converts.

**Step-by-Step Walkthrough:**

**Step 1: Write Killer Ad Copy ✨**
- Open Ad Copy & Creative Lab in HustleLab
- Input: your product, target customer, and key benefit
- Generate 5–10 variations of:
  - Hooks (first line)
  - Body copy (2–3 sentences)
  - Call-to-action (CTA)
- Pick your top 3 and save them

**Step 2: Find Your Audience 🎯**
- Use Audience Magnet to generate targeting ideas
- AI suggests:
  - Interest-based audiences
  - Lookalike seeds
  - Demographic breakdowns
- Write down 3 audience segments to test

**Step 3: Create Ad Visuals**
- Use product photos or lifestyle shots from supplier
- Add text overlays using Canva (free)
- Try 3 formats: single image, carousel, video (use TikTok-style clips if possible)
- Keep it native: ads should look like regular posts

**Step 4: Set Up Meta Ads Manager**
- Go to Facebook Ads Manager (business.facebook.com)
- Create a new campaign: choose "Sales" objective
- Set budget: $10–20/day to start
- Use one ad set per audience
- Upload your ad creative + copy
- Link to your product page or homepage

**Step 5: Install Meta Pixel**
- Add Meta Pixel to your Shopify/Wix store
- This tracks visitors and conversions
- Test it using the Pixel Helper Chrome extension

**HustleLab Tools Used:**
- ✨ Ad Copy & Creative Lab → ad scripts
- 🎯 Audience Magnet → targeting strategy

**Platform Actions:**
- Meta Ads Manager account created
- Pixel installed on store
- First campaign launched

**Daily Mission:**
Launch your ad. Don't wait for perfection. Set it live and monitor for 24 hours. Take a screenshot when your first ad impression hits.

**Motivational Close:**
You're live. Real people are seeing your brand right now. That's the difference between dreamers and doers. You're in the game.`
      },
      {
        id: "day-6",
        title: "DAY 6: Optimize, Track & Scale What Works",
        duration: "Day 6 - 1 hour",
        content: `**Today's Goal:**
Analyze your ad performance, kill what's not working, and double down on winners.

**What You're Building Today:**
A data-driven mindset. The best marketers don't guess — they test, measure, and scale. Today, you become one of them.

**Step-by-Step Walkthrough:**

**Step 1: Check Your Metrics**
Open Meta Ads Manager and look at:
- CTR (Click-Through Rate): Above 1.5% is good
- CPC (Cost Per Click): Under $1 is solid
- ROAS (Return on Ad Spend): 2x or higher = profitable

If CTR is low: change creative or hook
If CPC is high: narrow your audience or improve creative
If no sales yet: check your landing page and offer

**Step 2: Use Budget Booster for Insights 📊**
- Open Budget Booster in HustleLab
- Input your spend, clicks, and conversions
- AI suggests:
  - Where to reallocate budget
  - Which audiences to pause
  - Which creatives to scale

**Step 3: Split Test Like a Pro**
- Duplicate your best-performing ad
- Change ONE thing: headline, image, or audience
- Run both for 48 hours
- Keep the winner, kill the loser

**Step 4: Retarget Warm Traffic**
Create a retargeting campaign for:
- Store visitors who didn't buy
- Add-to-cart abandoners
- Use a discount code or urgency angle
- Budget: $5–10/day

**Step 5: Monitor Daily**
- Check your ads every morning and evening
- Pause anything with $10+ spend and no results
- Scale winners by 20–30% every 2 days

**HustleLab Tools Used:**
- 📊 Budget Booster → ad optimization

**Platform Actions:**
- Adjust Meta Ads Manager settings
- Create retargeting audience
- Launch split tests

**Daily Mission:**
Screenshot your best-performing ad and share it in a Discord, group chat, or with a friend. Celebrate small wins.

**Motivational Close:**
This is where most people quit. You're not most people. You're testing, learning, and improving. That's the entrepreneur's edge.`
      },
      {
        id: "day-7",
        title: "DAY 7: Get Your First Sale & Plan Your Scale",
        duration: "Day 7 - 1 hour",
        content: `**Today's Goal:**
Make your first sale (if you haven't already) and create a 30-day growth roadmap.

**What You're Building Today:**
Momentum. One sale proves the system works. Now you just need to repeat it 10x, 100x, 1000x.

**Step-by-Step Walkthrough:**

**Step 1: Push for the First Sale**
If you haven't sold yet:
- Increase ad budget by 50%
- Offer a limited-time discount (24-hour flash sale)
- Post organic content on TikTok, Instagram, or Facebook
- Message friends/family to support (they count!)

If you have sold:
- Celebrate! (Seriously, take a moment)
- Screenshot the order notification

**Step 2: Fulfill the Order Like a Pro**
- Order the product from your supplier
- Use the customer's shipping address
- Send a tracking number within 24 hours
- Follow up with a thank-you email

**Step 3: Ask for a Review**
- 3–5 days after delivery, send a friendly email
- Offer a small incentive (10% off next order)
- Use the review on your store and in future ads

**Step 4: Build Your 30-Day Roadmap**
- Week 1–2: Test 5+ ad creatives, find your winners
- Week 3: Scale winning ads by 2–3x
- Week 4: Launch new products or test organic content (TikTok/Reels)
- Goal: $500–$1,000 in revenue by Day 30

**Step 5: Reinvest Your Profits**
- First $100: put back into ads
- First $500: buy more inventory or test new products
- First $1,000: hire a VA or content creator

**Step 6: Set Up Email Marketing (Bonus)**
Use Klaviyo, Mailchimp, or Shopify Email to set up:
- Welcome series
- Abandoned cart emails
- Post-purchase follow-up

This turns one-time buyers into repeat customers.

**HustleLab Tools Used:**
All tools revisited for ongoing optimization

**Platform Actions:**
- Fulfill first order
- Set up email automation
- Plan next product launch

**Daily Mission:**
Write down your revenue goal for Month 1. Make it realistic but exciting. Then reverse-engineer how many sales you need per day.

**Motivational Close:**
You did it. You went from idea to live store to first sale in 7 days. That's faster than 99% of people who "want to start a business." Now the real fun begins — scaling.

---

## 🚀 FAST TRACK YOUR HUSTLE: The Recap

**You just built a real business in one week.**

Here's what you accomplished:
✅ Chose a profitable niche
✅ Found trending products
✅ Built a brand from scratch
✅ Launched a professional store
✅ Created high-converting offers
✅ Ran your first ad campaign
✅ Made your first sale (or you're about to)

And you did it all using HustleLab.

**What's Next?**

Your Next 30 Days:
- Scale your winning ads
- Test new products every week
- Build your email list
- Create organic content (TikTok, Reels, Pinterest)
- Hit $1,000–$5,000/month

Your Next 90 Days:
- Expand to new niches or go deeper in your current one
- Hire a virtual assistant or content creator
- Build a brand people recognize and trust
- Hit $5,000–$10,000/month

**Remember:**
Speed beats perfection.
Testing beats guessing.
Action beats analysis paralysis.

Everything you need to create, launch, and scale lives inside HustleLab. The tools are built. The roadmap is clear.

Now go build your empire. 💰⚡`
      }
    ],
    proTips: [
      "Speed beats perfection - launch fast and iterate",
      "Test 5+ ad creatives to find your winners",
      "Reinvest first $100 profit back into ads",
      "Use UGC (user-generated content) to validate products before sourcing",
      "Set up email marketing early for repeat customers",
      "Track ROAS daily - pause anything with $10+ spend and no results",
      "Scale winning ads by 20-30% every 2 days"
    ]
  }
];
