import { Course } from "@/types/course";

export const courses: Course[] = [
  {
    id: "7-day-dropshipping-sprint",
    title: "The 7-Day Dropshipping Sprint",
    emoji: "📦",
    shortDescription: "Launch a profitable store and make your first sale in one week using AI-powered tools.",
    fullDescription: "Launch Your Store and Make Your First Sale in One Week. This comprehensive 7-day program takes you from zero to your first sale using Hustle Lab's AI-powered tools. No guesswork, no fluff—just a proven system that helps you build, launch, and scale a real dropshipping business.",
    difficulty: "Beginner",
    estimatedTime: "7 days (1-2 hours per day)",
    toolsUsed: [
      "biz-idea",
      "dropship-goldmine",
      "name-forge",
      "offer-builder",
      "ad-copy-lab"
    ],
    prerequisites: [
      "Hustle Lab Pro subscription",
      "$10-20 ad budget for testing",
      "Shopify or Wix account (14-day free trial available)",
      "Basic understanding of e-commerce"
    ],
    expectedOutcomes: [
      "Launch a professional dropshipping store from scratch",
      "Choose a profitable niche with trending products",
      "Create a complete brand identity (name, logo, colors)",
      "Set up high-converting product pages and offers",
      "Launch and optimize Meta ad campaigns",
      "Make your first sale within 7 days",
      "Build a 30-day growth roadmap for $1,000+ revenue"
    ],
    modules: [
      {
        id: "day-1",
        title: "DAY 1: Find Your Million-Dollar Niche",
        duration: "Day 1 - 30 minutes",
        toolsUsed: ["biz-idea", "dropship-goldmine"],
        content: `**Today's Goal:**
Choose a profitable niche and find 3–5 winning products you can sell immediately.

**What You're Building Today:**
Your foundation. No store can succeed without a focused niche and products people actually want to buy. Today, you're using AI to cut through the noise and find what's already working.

**Step-by-Step Walkthrough:**

**Step 1: Fire Up the Biz-Idea Reactor 💡**
- Open HustleLab and navigate to Biz-Idea Reactor
- Enter your interests or leave it blank for AI suggestions
- Review 5–10 niche ideas generated by the tool
- Look for niches with high demand, low saturation, and emotional appeal (fitness, pets, self-care, home improvement)

**Step 2: Validate with Dropship Goldmine 📦**
- Jump into Dropship Goldmine
- Enter your chosen niche (e.g., "pet accessories" or "home gym equipment")
- Let AI pull trending products from suppliers
- Filter by: order volume, profit margin, and shipping time
- Bookmark 3–5 products that have strong visuals and reviews

**Step 3: Quick Market Check**
- Search your top product on Amazon, TikTok, and Instagram
- Check if there's UGC (user-generated content) around it
- If people are already creating content about it, that's your green light

**HustleLab Tools Used:**
- 💡 Biz-Idea Reactor → niche selection
- 📦 Dropship Goldmine → product research

**Platform Actions:**
None yet — today is pure research and decision-making

**Daily Mission:**
Write down your niche and your top 3 products in a Google Doc or Notes app. Include the supplier link and estimated profit per unit.

**Motivational Close:**
You just did in 30 minutes what most people spend weeks overthinking. You have your niche. You have your products. Now let's build the brand around them.`
      },
      {
        id: "day-2",
        title: "DAY 2: Build Your Brand Identity",
        duration: "Day 2 - 1-2 hours",
        toolsUsed: ["name-forge"],
        content: `**Today's Goal:**
Create a memorable brand name, logo, and visual identity that makes your store look legit from day one.

**What You're Building Today:**
Your brand. This is what people will remember, share, and trust. You're not just another dropshipper — you're building something that feels real.

**Step-by-Step Walkthrough:**

**Step 1: Generate Your Brand Name ⚡**
- Open Name Forge in HustleLab
- Enter your niche + a few keywords (e.g., "pet," "premium," "cozy")
- Review 20+ brand name options
- Pick one that's short, memorable, and available as a .com domain
- Check availability on Namecheap or GoDaddy

**Step 2: Design Your Logo 🎨**
- Head to Logo Maker
- Enter your brand name and select your niche
- Choose a style: minimal, bold, playful, or elegant
- Download 3–5 logo variations (with and without text)
- Save as PNG with transparent background

**Step 3: Set Your Brand Colors**
- Pick 2–3 colors that match your niche vibe
- Use a tool like Coolors.co or let Logo Maker suggest a palette
- Write them down (hex codes) — you'll use these everywhere

**Step 4: Create a Simple Brand Guide**
In a doc, write:
- Brand name
- Tagline (1 sentence: what you sell + who it's for)
- Color palette
- Font style (clean and modern works for most niches)

**HustleLab Tools Used:**
- ⚡ Name Forge → brand name
- 🎨 Logo Maker → logo design

**Platform Actions:**
- Register your domain (optional but recommended)
- Create a branded email (use Gmail or domain email)

**Daily Mission:**
Post your logo and brand name in a story or tweet. Tag it #7DaySprint. Accountability = momentum.

**Motivational Close:**
Your brand exists now. It has a name, a face, and a vibe. People will buy from brands, not random stores. You're already ahead of 90% of beginners.`
      },
      {
        id: "day-3",
        title: "DAY 3: Build Your Store in Under 2 Hours",
        duration: "Day 3 - 2 hours",
        toolsUsed: ["offer-builder"],
        content: `**Today's Goal:**
Set up a live Shopify or Wix store with your products, branding, and checkout ready to go.

**What You're Building Today:**
Your storefront. This is where the magic happens. No fluff, no distractions — just a clean, conversion-focused store.

**Step-by-Step Walkthrough:**

**Step 1: Choose Your Platform**
- Shopify (recommended): 14-day free trial, built for e-commerce
- Wix: easier for beginners, decent e-commerce tools
- Sign up and pick a clean, mobile-friendly theme

**Step 2: Use Store Layout Wizard 🏗️**
- Open Store Layout Wizard in HustleLab
- Enter your niche and product types
- AI generates a homepage structure: hero section, featured products, trust badges, FAQ
- Follow the layout and replicate it in your Shopify/Wix editor

**Step 3: Add Your Products**
- Upload product photos from your supplier
- Write product titles (keep them benefit-focused)
- Use Offer Builder 🎁 to generate compelling product descriptions
- Set your pricing: cost + 2–3x markup (aim for $15–$50 profit per item)

**Step 4: Essential Pages**
- Create: Home, Shop, About Us, Contact, Shipping Policy, Refund Policy
- Use AI or templates for policy pages (Shopify has built-in generators)

**Step 5: Connect Payment & Shipping**
- Add PayPal and Stripe (or Shopify Payments)
- Set shipping zones and rates (or offer free shipping and bake it into price)
- Enable email notifications for orders

**Step 6: Add Trust Elements**
- Security badges (SSL, payment icons)
- Reviews section (use app like Loox or Judge.me)
- Live chat widget (Tidio or Gorgias free plan)

**HustleLab Tools Used:**
- 🏗️ Store Layout Wizard → store structure
- 🎁 Offer Builder → product descriptions

**Platform Actions:**
- Shopify or Wix account created
- Theme installed
- Products uploaded
- Payments connected

**Daily Mission:**
Place a test order on your own store. Make sure everything works: cart, checkout, email confirmation.

**Motivational Close:**
Your store is live. You can send someone a link right now and they can buy from you. That's powerful. Most people never get this far.`
      },
      {
        id: "day-4",
        title: "DAY 4: Create Irresistible Offers & Upsells",
        duration: "Day 4 - 1 hour",
        toolsUsed: ["offer-builder"],
        content: `**Today's Goal:**
Increase your average order value by 30–50% using smart upsells, bundles, and urgency tactics.

**What You're Building Today:**
Profit maximizers. Every customer is valuable — your job is to make the most of every transaction without being pushy.

**Step-by-Step Walkthrough:**

**Step 1: Build Product Bundles 🎁**
- Use Offer Builder to create 2–3 bundle ideas
- Example: "Starter Kit," "Best Seller Bundle," "Complete Set"
- Offer a discount (10–15% off) when bought together
- Add bundles as separate products on your store

**Step 2: Add Upsells with Upsell Creator 💰**
- Open Upsell Creator in HustleLab
- Input your main product
- AI suggests complementary upsell/cross-sell items
- Install a Shopify app like Zipify OCU, UpCart, or Honeycomb
- Set up post-purchase or cart upsells

**Step 3: Create Urgency Without Being Sleazy**
- Add countdown timers to product pages (use apps like Hurrify)
- Show stock levels: "Only 7 left in stock"
- Offer limited-time discounts for first-time buyers

**Step 4: Write a Killer Welcome Offer**
- Use Offer Builder to create a popup or banner offer
- Example: "Get 15% off your first order + free shipping"
- Install an email capture popup (Privy, Klaviyo, or Shopify native)

**HustleLab Tools Used:**
- 🎁 Offer Builder → bundles and promotions
- 💰 Upsell Creator → upsell strategy

**Platform Actions:**
- Install upsell app on Shopify/Wix
- Add bundles as products
- Set up email popup with discount code

**Daily Mission:**
Write down your average order value (AOV) goal. If your product is $30, aim for $45–50 with upsells.

**Motivational Close:**
You're not just selling products anymore. You're building a system that prints profit. One customer, multiple revenue streams.`
      },
      {
        id: "day-5",
        title: "DAY 5: Launch Your First Ad Campaign",
        duration: "Day 5 - 1-2 hours",
        toolsUsed: ["ad-copy-lab"],
        content: `**Today's Goal:**
Create and launch a Meta (Facebook/Instagram) ad campaign with scroll-stopping creative and copy.

**What You're Building Today:**
Your customer acquisition engine. Organic is great, but paid ads bring speed. Today, you learn how to buy traffic that converts.

**Step-by-Step Walkthrough:**

**Step 1: Write Killer Ad Copy ✨**
- Open Ad Copy & Creative Lab in HustleLab
- Input: your product, target customer, and key benefit
- Generate 5–10 variations of:
  - Hooks (first line)
  - Body copy (2–3 sentences)
  - Call-to-action (CTA)
- Pick your top 3 and save them

**Step 2: Find Your Audience 🎯**
- Use Audience Magnet to generate targeting ideas
- AI suggests:
  - Interest-based audiences
  - Lookalike seeds
  - Demographic breakdowns
- Write down 3 audience segments to test

**Step 3: Create Ad Visuals**
- Use product photos or lifestyle shots from supplier
- Add text overlays using Canva (free)
- Try 3 formats: single image, carousel, video (use TikTok-style clips if possible)
- Keep it native: ads should look like regular posts

**Step 4: Set Up Meta Ads Manager**
- Go to Facebook Ads Manager (business.facebook.com)
- Create a new campaign: choose "Sales" objective
- Set budget: $10–20/day to start
- Use one ad set per audience
- Upload your ad creative + copy
- Link to your product page or homepage

**Step 5: Install Meta Pixel**
- Add Meta Pixel to your Shopify/Wix store
- This tracks visitors and conversions
- Test it using the Pixel Helper Chrome extension

**HustleLab Tools Used:**
- ✨ Ad Copy & Creative Lab → ad scripts
- 🎯 Audience Magnet → targeting strategy

**Platform Actions:**
- Meta Ads Manager account created
- Pixel installed on store
- First campaign launched

**Daily Mission:**
Launch your ad. Don't wait for perfection. Set it live and monitor for 24 hours. Take a screenshot when your first ad impression hits.

**Motivational Close:**
You're live. Real people are seeing your brand right now. That's the difference between dreamers and doers. You're in the game.`
      },
      {
        id: "day-6",
        title: "DAY 6: Optimize, Track & Scale What Works",
        duration: "Day 6 - 1 hour",
        content: `**Today's Goal:**
Analyze your ad performance, kill what's not working, and double down on winners.

**What You're Building Today:**
A data-driven mindset. The best marketers don't guess — they test, measure, and scale. Today, you become one of them.

**Step-by-Step Walkthrough:**

**Step 1: Check Your Metrics**
Open Meta Ads Manager and look at:
- CTR (Click-Through Rate): Above 1.5% is good
- CPC (Cost Per Click): Under $1 is solid
- ROAS (Return on Ad Spend): 2x or higher = profitable

If CTR is low: change creative or hook
If CPC is high: narrow your audience or improve creative
If no sales yet: check your landing page and offer

**Step 2: Use Budget Booster for Insights 📊**
- Open Budget Booster in HustleLab
- Input your spend, clicks, and conversions
- AI suggests:
  - Where to reallocate budget
  - Which audiences to pause
  - Which creatives to scale

**Step 3: Split Test Like a Pro**
- Duplicate your best-performing ad
- Change ONE thing: headline, image, or audience
- Run both for 48 hours
- Keep the winner, kill the loser

**Step 4: Retarget Warm Traffic**
Create a retargeting campaign for:
- Store visitors who didn't buy
- Add-to-cart abandoners
- Use a discount code or urgency angle
- Budget: $5–10/day

**Step 5: Monitor Daily**
- Check your ads every morning and evening
- Pause anything with $10+ spend and no results
- Scale winners by 20–30% every 2 days

**HustleLab Tools Used:**
- 📊 Budget Booster → ad optimization

**Platform Actions:**
- Adjust Meta Ads Manager settings
- Create retargeting audience
- Launch split tests

**Daily Mission:**
Screenshot your best-performing ad and share it in a Discord, group chat, or with a friend. Celebrate small wins.

**Motivational Close:**
This is where most people quit. You're not most people. You're testing, learning, and improving. That's the entrepreneur's edge.`
      },
      {
        id: "day-7",
        title: "DAY 7: Get Your First Sale & Plan Your Scale",
        duration: "Day 7 - 1 hour",
        content: `**Today's Goal:**
Make your first sale (if you haven't already) and create a 30-day growth roadmap.

**What You're Building Today:**
Momentum. One sale proves the system works. Now you just need to repeat it 10x, 100x, 1000x.

**Step-by-Step Walkthrough:**

**Step 1: Push for the First Sale**
If you haven't sold yet:
- Increase ad budget by 50%
- Offer a limited-time discount (24-hour flash sale)
- Post organic content on TikTok, Instagram, or Facebook
- Message friends/family to support (they count!)

If you have sold:
- Celebrate! (Seriously, take a moment)
- Screenshot the order notification

**Step 2: Fulfill the Order Like a Pro**
- Order the product from your supplier
- Use the customer's shipping address
- Send a tracking number within 24 hours
- Follow up with a thank-you email

**Step 3: Ask for a Review**
- 3–5 days after delivery, send a friendly email
- Offer a small incentive (10% off next order)
- Use the review on your store and in future ads

**Step 4: Build Your 30-Day Roadmap**
- Week 1–2: Test 5+ ad creatives, find your winners
- Week 3: Scale winning ads by 2–3x
- Week 4: Launch new products or test organic content (TikTok/Reels)
- Goal: $500–$1,000 in revenue by Day 30

**Step 5: Reinvest Your Profits**
- First $100: put back into ads
- First $500: buy more inventory or test new products
- First $1,000: hire a VA or content creator

**Step 6: Set Up Email Marketing (Bonus)**
Use Klaviyo, Mailchimp, or Shopify Email to set up:
- Welcome series
- Abandoned cart emails
- Post-purchase follow-up

This turns one-time buyers into repeat customers.

**HustleLab Tools Used:**
All tools revisited for ongoing optimization

**Platform Actions:**
- Fulfill first order
- Set up email automation
- Plan next product launch

**Daily Mission:**
Write down your revenue goal for Month 1. Make it realistic but exciting. Then reverse-engineer how many sales you need per day.

**Motivational Close:**
You did it. You went from idea to live store to first sale in 7 days. That's faster than 99% of people who "want to start a business." Now the real fun begins — scaling.

---

## 🚀 FAST TRACK YOUR HUSTLE: The Recap

**You just built a real business in one week.**

Here's what you accomplished:
✅ Chose a profitable niche
✅ Found trending products
✅ Built a brand from scratch
✅ Launched a professional store
✅ Created high-converting offers
✅ Ran your first ad campaign
✅ Made your first sale (or you're about to)

And you did it all using HustleLab.

**What's Next?**

Your Next 30 Days:
- Scale your winning ads
- Test new products every week
- Build your email list
- Create organic content (TikTok, Reels, Pinterest)
- Hit $1,000–$5,000/month

Your Next 90 Days:
- Expand to new niches or go deeper in your current one
- Hire a virtual assistant or content creator
- Build a brand people recognize and trust
- Hit $5,000–$10,000/month

**Remember:**
Speed beats perfection.
Testing beats guessing.
Action beats analysis paralysis.

Everything you need to create, launch, and scale lives inside HustleLab. The tools are built. The roadmap is clear.

Now go build your empire. 💰⚡`
      }
    ],
    proTips: [
      "Speed beats perfection - launch fast and iterate",
      "Test 5+ ad creatives to find your winners",
      "Reinvest first $100 profit back into ads",
      "Use UGC (user-generated content) to validate products before sourcing",
      "Set up email marketing early for repeat customers",
      "Track ROAS daily - pause anything with $10+ spend and no results",
      "Scale winning ads by 20-30% every 2 days"
    ]
  },
  {
    id: "digital-product-empire",
    title: "The Digital Product Empire: From Idea to Income",
    emoji: "🚀",
    shortDescription: "Create and sell your first digital product in one week using AI-powered tools",
    fullDescription: "A 7-Day HustleLab Course for Digital Creators. Your fast-track blueprint to creating and selling your first digital product in just 7 days. This isn't theory. This isn't \"someday.\" This is your week to build, launch, and start earning. You're going to use HustleLab's AI-powered tools to go from blank page to published product across multiple platforms. No design degree needed. No coding required. Just you, HustleLab, and a commitment to move fast.",
    difficulty: "Beginner",
    estimatedTime: "7 days (1-2 hours per day)",
    toolsUsed: [
      "biz-idea",
      "name-forge",
      "bookforge",
      "logomaker",
      "offer-builder",
      "hook-factory",
      "page-builder",
      "inbox-influence"
    ],
    prerequisites: [
      "HustleLab account with access to content creation tools",
      "Accounts on Gumroad, Etsy, and Whop (or willingness to create them)",
      "Basic understanding of digital products",
      "Social media presence (optional but helpful for promotion)"
    ],
    expectedOutcomes: [
      "Launch a complete digital product (ebook/guide) in 7 days",
      "List your product on 3+ selling platforms (Gumroad, Etsy, Whop)",
      "Create professional cover and brand assets using AI",
      "Write high-converting sales copy and landing pages",
      "Set up automated sales and delivery systems",
      "Develop a social media and email promotion strategy",
      "Generate your first sales and collect testimonials",
      "Build a 30-day growth roadmap for scaling your digital product business"
    ],
    proTips: [
      "Speed beats perfection - launch fast and iterate based on feedback",
      "Done is better than perfect - ship your first draft and improve later",
      "Pricing is a test, not a tattoo - you can always adjust after launch",
      "Design fast, launch faster - don't let perfect design slow you down",
      "Marketing isn't bragging, it's serving - promote your solution confidently",
      "Published beats polished - the market rewards action over preparation",
      "Collect testimonials early - they're your best sales tool",
      "Small systems = big results - automate early to scale effortlessly",
      "Repurpose content across platforms - one ebook can become multiple income streams"
    ],
    modules: [
      {
        id: "day-1-niche",
        title: "Find Your Profitable Niche",
        duration: "Day 1 - 30 minutes",
        toolsUsed: ["biz-idea"],
        content: `**Today's Goal**

Discover a winning digital product idea that people actually want to buy — and validate it fast.

**Why This Matters**

You can't sell what nobody wants. Day 1 is about smart research, not guessing. We're finding profitable niches where buyers are already spending money.

**Step-by-Step Instructions**

**Step 1: Open Biz-Idea Reactor**

- Launch HustleLab's 💡 Biz-Idea Reactor
- Enter your interests, skills, or general topics (e.g., "fitness," "productivity," "side hustles," "budgeting")
- Let the AI generate 10+ validated niche ideas with market demand scores

**Step 2: Filter for Digital Product Fit**

Look for niches that match digital products like:
- How-to guides
- Templates and worksheets
- Checklists and planners
- Step-by-step tutorials
- Niche-specific resources

**Step 3: Validate on External Platforms**

Quick-check your top 3 ideas:
- **Etsy**: Search your niche + "digital download" — are there listings with 100+ sales?
- **Gumroad**: Browse trending products in your category
- **Whop**: Check if similar digital products exist and have active communities

**Step 4: Choose Your Niche**

Pick ONE niche you're confident about. Write it down:
- My Niche: _______________________
- Target Audience: _______________________
- Product Type: (ebook/guide/template/planner)

**HustleLab Tools Used**

- 💡 Biz-Idea Reactor — niche discovery and validation

**External Platforms to Research**

- Etsy.com (search trends)
- Gumroad.com (browse bestsellers)
- Whop.com (check active marketplaces)

**Quick-Action Challenge**

Set a 20-minute timer. Use Biz-Idea Reactor, pick your niche, and validate it on 2 platforms. No overthinking. If people are buying it, it's viable.

**Motivational Close**

"Your niche doesn't need to be perfect — it needs to be profitable. Pick one and move. Speed = sales."`
      },
      {
        id: "day-2-content",
        title: "Build Your Ebook Outline & Content",
        duration: "Day 2 - 1-2 hours",
        toolsUsed: ["name-forge", "bookforge"],
        content: `**Today's Goal**

Create a complete, high-value ebook or digital guide using AI — no writer's block, no excuses.

**Why This Matters**

Content is your product. Today, you're going from idea to finished manuscript. HustleLab does the heavy lifting — you just guide it.

**Step-by-Step Instructions**

**Step 1: Craft Your Product Concept**

Answer these quick questions:
- What problem does my product solve?
- Who is it for?
- What outcome will they get?

**Step 2: Use Name Forge to Title Your Product**

- Open ⚡ Name Forge
- Input your niche and target audience
- Generate 10+ product name options
- Choose one that's clear, catchy, and benefit-driven

Example: "The 30-Day Budget Reset" or "Freelancer's First Client Blueprint"

**Step 3: Launch BookForge for Content Creation**

- Open 📚 BookForge
- Enter your product name and niche
- Provide a brief outline or let AI generate one (8–12 chapters recommended)
- Generate your complete ebook or guide content

**Step 4: Review and Customize**

- Read through the AI-generated content
- Add personal stories, examples, or bonus tips
- Make it sound like YOU (authenticity sells)

**Step 5: Format for Readability**

- Break content into clear sections
- Add subheadings, bullet points, and action steps
- Keep paragraphs short and scannable

**HustleLab Tools Used**

- ⚡ Name Forge — product naming
- 📚 BookForge — full ebook/guide creation

**External Platforms to Check**

None today — stay focused on creation

**Quick-Action Challenge**

Generate your full ebook draft in one session. Don't edit as you go. Let the AI build it, then refine. Aim to have a complete manuscript by end of day.

**Motivational Close**

"Done is better than perfect. Your first draft is your first step to profit. Write it. Ship it. Improve it later."`
      },
      {
        id: "day-3-design",
        title: "Design Your Cover & Brand Assets",
        duration: "Day 3 - 30 minutes",
        toolsUsed: ["bookforge", "logomaker"],
        content: `**Today's Goal**

Create a professional, eye-catching cover and branding that makes your product look premium.

**Why This Matters**

People judge digital products by their covers. A strong visual = higher perceived value = more sales.

**Step-by-Step Instructions**

**Step 1: Generate Your Ebook Cover**

- Open 📖 BookForge Cover Maker
- Input your product name and niche
- Choose a style: modern, minimalist, bold, elegant
- Generate 5+ cover options
- Select your favorite and download in high resolution

**Step 2: Create Supporting Brand Assets**

- Open 🎨 Logo Maker
- Design a simple logo or brand mark for your product line
- Use consistent colors and fonts across all assets

**Step 3: Design Interior Graphics (Optional)**

If your guide includes worksheets or planners:
- Use BookForge or Logo Maker to create section headers
- Keep design clean and print-friendly

**Step 4: Package Your Product**

Create your final files:
- PDF format (standard for ebooks/guides)
- EPUB format (optional, for wider compatibility)
- Name your file professionally: ProductName_v1.pdf

**Step 5: Create a Mockup**

- Use free tools like Canva or Placeit to create a 3D mockup of your ebook
- This will be used in your sales listings and promotions

**HustleLab Tools Used**

- 📖 BookForge Cover Maker — professional cover design
- 🎨 Logo Maker — branding assets

**External Platforms to Use**

- Canva.com (optional mockups)
- Placeit.net (optional 3D product mockups)

**Quick-Action Challenge**

Design and finalize your cover in 30 minutes. Pick one, commit, and move on. Remember: a published product with a "good enough" cover beats a perfect cover that never launches.

**Motivational Close**

"Your cover is your first impression. Make it count, but don't let it slow you down. Design fast. Launch faster."`
      },
      {
        id: "day-4-pricing",
        title: "Create Your Irresistible Offer & Pricing",
        duration: "Day 4 - 1 hour",
        toolsUsed: ["offer-builder"],
        content: `**Today's Goal**

Position your product as a no-brainer purchase with the right price, bonuses, and messaging.

**Why This Matters**

Pricing isn't random — it's psychology. Today you'll craft an offer so compelling that buyers can't say no.

**Step-by-Step Instructions**

**Step 1: Research Competitor Pricing**

Quick scan on your target platforms:
- **Etsy**: What are similar digital products priced at?
- **Gumroad**: Check the $7–$27 sweet spot for guides
- **Whop**: Look at premium digital products ($19–$49)

**Step 2: Use Offer Builder to Structure Your Offer**

- Open 🎁 Offer Builder
- Input your product details and target audience
- Generate multiple offer variations with:
  - Core product
  - Bonus materials (checklists, templates, email swipes)
  - Limited-time pricing or early-bird discounts
  - Money-back guarantee language

**Step 3: Choose Your Pricing Strategy**

Pick one based on your niche and audience:

**Budget-Friendly ($7–$15):**
- High volume, impulse buy
- Great for broad niches

**Mid-Tier ($17–$27):**
- Best for how-to guides and actionable content
- Perceived as premium but accessible

**Premium ($37–$49):**
- For in-depth guides with templates, bonuses, or community access
- Requires strong positioning

**Step 4: Create Your Product Description**

Use Offer Builder output to write:
- A compelling headline (what they'll achieve)
- 3–5 bullet points (key benefits)
- Social proof or credibility statement
- Clear call-to-action

**Step 5: Add Bonuses (Even Small Ones)**

Examples:
- Printable checklist
- Email template pack
- Quick-start guide
- Access to a private community (Whop exclusive)

**HustleLab Tools Used**

- 🎁 Offer Builder — pricing, positioning, and bonuses

**External Platforms to Research**

- Etsy, Gumroad, Whop (competitor pricing research)

**Quick-Action Challenge**

Set your price and lock it in. Don't second-guess. You can always test and adjust after launch. Pick a number and commit.

**Motivational Close**

"Pricing is a test, not a tattoo. Set it, launch it, learn from it. The market will tell you what works — but only if you publish."`
      },
      {
        id: "day-5-launch",
        title: "Build Your Sales Page & Upload Listings",
        duration: "Day 5 - 2 hours",
        toolsUsed: ["hook-factory", "page-builder"],
        content: `**Today's Goal**

Create high-converting sales pages and upload your product to at least 3 platforms.

**Why This Matters**

You can't make money if no one can buy. Today is about visibility and access — getting your product in front of buyers.

**Step-by-Step Instructions**

**Step 1: Write Your Sales Copy**

- Open 🪝 Hook Factory
- Generate 10+ headline options for your sales page
- Choose the most compelling hook
- Use Offer Builder output for body copy

**Step 2: Build Your Sales Page (Choose One Path)**

**Option A: Use HustleLab's Page & Profile Builder**
- Open 📱 Page & Profile Builder
- Select "Sales Page" template
- Input your product name, description, pricing, and bonuses
- Customize colors and layout
- Publish your page and copy the link

**Option B: Create a Standalone Landing Page**

Use tools like:
- Stan Store (easiest for creators)
- Carrd.co (simple, clean pages)
- Beacons.ai (link-in-bio with sales functionality)

**Step 3: Upload to Platform #1 — Gumroad**

- Go to Gumroad.com and create a free account
- Click "New Product" → Upload your PDF
- Add product name, description, cover image, and price
- Enable "Pay What You Want" (optional for higher conversions)
- Publish your listing

**Step 4: Upload to Platform #2 — Etsy**

- Create an Etsy seller account (if you don't have one)
- List your product under "Digital Downloads"
- Upload your PDF and cover mockup
- Write SEO-friendly title and tags (use your niche keywords)
- Set your price and enable instant download
- Publish

**Step 5: Upload to Platform #3 — Whop**

- Sign up as a creator on Whop.com
- Create a new product or "experience"
- Upload your ebook as a digital download
- Add product description and pricing
- Enable affiliate commission options (to let others promote you)
- Launch

**Step 6: Optional Platform — Stan Store or Shopify**

If you want a branded experience:
- Stan Store: Great for creators with social followings
- Shopify Digital Downloads: Best if you want full control and branding

**HustleLab Tools Used**

- 🪝 Hook Factory — sales page headlines
- 📱 Page & Profile Builder — landing page creation

**External Platforms to Upload**

- Gumroad.com ✅
- Etsy.com ✅
- Whop.com ✅
- Stan Store (optional)
- Shopify (optional)

**Quick-Action Challenge**

Launch on all 3 platforms today. No delays. Upload, publish, and go live. Speed = momentum.

**Motivational Close**

"Your product is live. You're officially in business. Now it's time to let the world know."`
      },
      {
        id: "day-6-promote",
        title: "Promote Across Social & Email",
        duration: "Day 6 - 1 hour",
        toolsUsed: ["hook-factory", "inbox-influence", "logomaker"],
        content: `**Today's Goal**

Drive traffic to your product using organic promotion, social content, and email outreach.

**Why This Matters**

Listings don't sell themselves. Today you become your own best marketer — using AI to make it easy.

**Step-by-Step Instructions**

**Step 1: Create Social Media Content**

- Open 🪝 Hook Factory
- Generate 10+ social media hooks and captions for:
  - Instagram posts/reels
  - TikTok videos
  - Twitter/X threads
  - LinkedIn posts (if B2B niche)

**Content Ideas:**
- Behind-the-scenes: "I just launched my first ebook in 6 days"
- Transformation post: "Before I had this guide, I struggled with [problem]"
- Value teaser: "Here are 3 tips from my new guide (link in bio)"
- Launch announcement: "It's live! My [product name] is officially available"

**Step 2: Design Promo Graphics**

Use Logo Maker or Canva to create:
- Instagram story templates
- Carousel posts
- Pinterest pins (great for Etsy traffic)

**Step 3: Write Your Email Promotion**

- Open 📧 Inbox Influence
- Generate email copy for:
  - Launch announcement (to your email list)
  - Friend/family outreach (personal ask for support)
  - Cold outreach to influencers or affiliates (if applicable)

**Email Structure:**
- Subject line: Use Hook Factory outputs
- Body: Short, benefit-driven, with clear CTA
- Link: Direct to your sales page or Gumroad link

**Step 4: Post Daily for 7 Days**

Create a simple promotion calendar:
- Day 1: Launch announcement
- Day 2: Testimonial or personal story
- Day 3: Share a free tip from the guide
- Day 4: Behind-the-scenes or creation process
- Day 5: User benefit or transformation
- Day 6: Limited-time bonus or discount
- Day 7: Final call to action

**Step 5: Leverage Platform-Specific Traffic**

- **Etsy**: Optimize your SEO with keywords in title, tags, and description
- **Gumroad**: Share on Twitter and tag @gumroad for potential feature
- **Whop**: Enable affiliates so others can promote your product for commission
- **Pinterest**: Pin your product with high-value keywords

**HustleLab Tools Used**

- 🪝 Hook Factory — social media captions and hooks
- 📧 Inbox Influence — email promotion copy
- 🎨 Logo Maker — promo graphics

**External Platforms to Promote On**

- Instagram, TikTok, Twitter/X, LinkedIn
- Pinterest (huge for Etsy traffic)
- Email list or personal contacts
- Facebook groups or Reddit (if niche-appropriate)

**Quick-Action Challenge**

Post about your product on 3 platforms today. Don't wait for the perfect post. Share your link, tell your story, and invite people to buy.

**Motivational Close**

"Marketing isn't bragging — it's serving. Your product solves a problem. Share it loud, share it proud."`
      },
      {
        id: "day-7-automate",
        title: "Automate Your Sales + Next Steps",
        duration: "Day 7 - 1 hour",
        toolsUsed: ["inbox-influence", "biz-idea", "offer-builder"],
        content: `**Today's Goal**

Set up systems to automate your sales, track performance, and scale your digital product empire.

**Why This Matters**

You've launched. Now it's time to optimize, automate, and multiply. Today you build a system that works while you sleep.

**Step-by-Step Instructions**

**Step 1: Set Up Sales Automation**

**On Gumroad:**
- Enable automated delivery (already built-in)
- Set up email sequences for buyers (upsells, testimonials, referrals)

**On Etsy:**
- Use automated thank-you messages
- Enable auto-renewal for listings

**On Whop:**
- Enable affiliate program so others can sell for you
- Set up automated welcome messages for buyers

**Step 2: Track Your Sales & Analytics**

Create a simple tracker (Google Sheets or Notion):
- Platform name
- Number of sales
- Revenue
- Traffic sources
- Conversion rate

Check daily for the first 2 weeks, then weekly.

**Step 3: Collect Testimonials**

- Send a follow-up email to buyers asking for feedback
- Use Inbox Influence to craft the outreach
- Post testimonials on social and in your listings

**Step 4: Plan Your First Upsell**

Now that you have a product, create complementary offers:
- **Upsell**: Premium version with templates or coaching
- **Cross-sell**: Related guide in a similar niche
- **Bundle**: Package 2–3 products at a discount

Use Biz-Idea Reactor and Offer Builder to plan your next product.

**Step 5: Scale Your Traffic**

Advanced moves for growth:
- Run low-cost ads (Facebook, Pinterest, TikTok)
- Partner with affiliates on Whop
- Guest post or collaborate with creators in your niche
- Repurpose your ebook into a mini-course (list on Whop or Gumroad)

**Step 6: Celebrate & Commit**

You did it. You went from idea to income in 7 days.

Now commit to the next 30 days:
- Promote daily
- Iterate based on feedback
- Launch your next product

**Course Summary**

**What You Accomplished:**

✅ Day 1: Found a profitable niche with Biz-Idea Reactor
✅ Day 2: Created a complete ebook with BookForge
✅ Day 3: Designed a professional cover with BookForge
✅ Day 4: Built an irresistible offer with Offer Builder
✅ Day 5: Launched on Gumroad, Etsy, and Whop
✅ Day 6: Promoted across social and email using Hook Factory & Inbox Influence
✅ Day 7: Automated your sales and planned your next move

**The HustleLab Advantage:**

From idea to creation to sales to automation — HustleLab powered every step. No guesswork. No writer's block. No design bottlenecks. Just fast, focused action and real results.

**What's Next?**

- Launch your next product (go deeper in your niche or explore a new one)
- Build a product suite (bundles = bigger sales)
- Scale with ads, affiliates, and automation
- Join the HustleLab community and share your wins

**Remember:**

Speed beats perfection. Action beats planning. Published beats polished. You're not just building products — you're building an empire.

**HustleLab Tools Used**

- 📧 Inbox Influence — follow-up and upsell emails
- 💡 Biz-Idea Reactor — next product ideation
- 🎁 Offer Builder — upsell and bundle creation

**External Platforms to Optimize**

- Gumroad (automated emails, upsells)
- Etsy (SEO optimization, reviews)
- Whop (affiliate activation)
- Google Sheets or Notion (sales tracking)

**Quick-Action Challenge**

Set up ONE automation today — whether it's an email sequence, affiliate link, or sales tracker. Small systems = big results.

**Motivational Close**

"You're not just a creator anymore — you're a digital entrepreneur. Keep building. Keep launching. The empire starts now."`
      }
    ]
  }
];
